### ISSUE TITLE
Change "Viet Nam" to "Vietnam"

### ISSUE THREAD

**Issue by kevinlaw91** [fannarsh/country-list#11]
https://github.com/fannarsh/country-list/blob/2cd57f574ddfd617ceb771efceea462cf1634597/data.json#L968

I don't know if it is intended, but in Wikipedia this is the correct spelling.
https://en.wikipedia.org/wiki/Vietnam

**Comment by fannarsh** [comment]
Viet Nam is correct according to the [ISO 3166 standard](https://en.wikipedia.org/wiki/ISO_3166-2).
And also
>"Viet Nam" was once common usage and is still used by the United Nations and by the Vietnamese government.
https://en.wikipedia.org/wiki/Names_of_Vietnam
