### ISSUE TITLE
Country Name of Taiwan should be corrected

### ISSUE THREAD

**Issue by foxymen9** [fannarsh/country-list#14]
Taiwan does not belong to China, so the country name should be Taiwan only instead of "Taiwan, Province of China"
https://en.wikipedia.org/wiki/Taiwan

**Comment by Gta-Cool** [comment]
👎 

@foxymen9 Yes you're right, however, following the ISO 3166 standard, the country name is still "Taiwan, Province of China"...

https://www.iso.org/obp/ui/#iso:code:3166:TW

**Comment by fannarsh** [comment]
Hi, 
I want this lib to keep using the ISO 3166 standard, which are names that are in use by the United Nations (UN). So I'm not changing the name until there is a new update from them.

**Comment by taimoorgit** [comment]
Just in case anyone is reading this issue, you can use the "overwrite" function to change the countries. 

```
// Don't want to offend anyone
  overwrite([
    {
      code: "TW",
      name: "Taiwan",
    },
  ]);
```
