### ISSUE TITLE
Add country

### ISSUE THREAD

**Issue by lexeech** [fannarsh/country-list#19]
Hi! Could you please add Moldova as MD? Thank you.

**Comment by fannarsh** [comment]
Hi,
Moldova is already added as "Moldova, Republic of" which is the ISO 3166 standard name
https://www.iso.org/obp/ui/#iso:code:3166:MD

But you can overwrite that in code by doing this
``` js
const { overwrite, getName } = require('country-list');
overwrite([{
  "code": "MD",
  "name": "Moldova"
}])

console.log(getName('MD')); // Moldova
```
