### ISSUE TITLE
Changes between v1.x and v2.x?

### ISSUE THREAD

**Issue by saranshbansal** [fannarsh/country-list#22]
I am currently on version 1 and just saw that the version 2 is also available. Can you tell me if there is a breaking change when going from 1 to 2 or not?
Also what is changed in version 2?

**Comment by saranshbansal** [comment]
Hey @fannarsh thanks for writing in. I've made these changes in my code and here is my complete component:
```

import React, { Component } from 'react';
import { MenuItem } from 'material-ui';
import { getCodeList } from 'country-list';
import map from 'lodash/map';
import sortBy from 'lodash/sortBy';
import SelectFormField from './common/SelectFormField';

class CountrySelectFormField extends Component {
  constructor() {
    super();

    const countryOptions = map(getCodeList(), (countryName, countryCode) => ({
      value: countryCode.toUpperCase(),
      label: countryName,
    }));

    const options = sortBy(countryOptions, 'label');

    this.state = {
      options,
    };
  }

  render() {
    return (
      <SelectFormField {...this.props}>
        {this.state.options.map(option => (
          <MenuItem key={option.value} value={option.value} primaryText={option.label} />
        ))}
      </SelectFormField>
    );
  }
}

export default CountrySelectFormField;

```

I don't know why it has become so slow and sluggish to render the list and select the country. Also it takes forever to submit a form (calling the actual post api) with this field in it. If i remove this field, my form submission (calling the api) happens immediately.

**Comment by fannarsh** [comment]
So you are experiencing version 2 being slower then version 1?

**Comment by saranshbansal** [comment]
@fannarsh yes exactly. This same code works instantly for v1.

**Comment by fannarsh** [comment]
I'm closing this since the original question has been answered.
