### ISSUE TITLE
United States of America (USA/US)

### ISSUE THREAD

**Issue by bkawk** [fannarsh/country-list#28]
Please can you add United States of America (USA / US)

**Comment by TrySound** [comment]
It's already here
https://github.com/fannarsh/country-list/blob/master/data.json#L944

**Comment by fannarsh** [comment]
Hi, 
`US` is already in the data at https://github.com/fannarsh/country-list/blob/master/data.json#L944
I don't support the three letter country codes (ISO 3166-1 alpha-3).

cheers

**Comment by fannarsh** [comment]
going to update the data for this aswell
