### ISSUE TITLE
'United Kingdom of Great Britain and Northern Ireland' (GB/GBR)

### ISSUE THREAD

**Issue by bkawk** [fannarsh/country-list#31]
Please add 'United Kingdom of Great Britain and Northern Ireland' (GB/GBR)

**Comment by TrySound** [comment]
https://github.com/fannarsh/country-list/blob/master/data.json#L939 ?

**Comment by fannarsh** [comment]
Hi,
`UK` is already in the data at https://github.com/fannarsh/country-list/blob/master/data.json#L939
I don't support the three letter country codes (ISO 3166-1 alpha-3).

cheers

**Comment by fannarsh** [comment]
The current dataset I'm using is displaying `GB` incorrectly
