### ISSUE TITLE
Changing Turkey to Türkiye

### ISSUE THREAD

**Issue by metecan** [fannarsh/country-list#47]
> International organizations like the United Nations, the World Trade Organization, and NATO have already adopted Türkiye (roughly pronounced as "tur-key-yay"), following a formal request from the Turkish authorities

Could you change Turkey to Türkiye?

**Comment by fannarsh** [comment]
An update will be released soon, there is a couple of more names that have changed as well.

**Comment by fannarsh** [comment]
version 2.3.0 has been released that includes this update.

**Comment by kkm** [comment]
For the time being, I'll downgrade for 'Turkey' mostly:
`npm i country-list@2.2.0`
