### ISSUE TITLE
 Support for 3 letter country codes?

### ISSUE THREAD

**Issue by markstos** [fannarsh/country-list#6]
Hello,

Thanks for this module. Would you have any interest in also supporting the "ISO 3166-1 alpha 3" codes? (The three letter country codes)?

I find multiple modules that can deal with the 2 letter codes, but currently no modules on npmjs.org that appear to be able to convert the 3 letter codes.

**Comment by fannarsh** [comment]
Thanks for the interest in this module and sorry for a such late reply.
The idea for this module was to provide access to the data from http://data.okfn.org/data/core/country-list, and I've decided to keep it that way.

So sorry, no support for other codes.
